### ISSUE TITLE
Error when running test method using method2.invoke

### ISSUE THREAD

**Issue by UttamAaseri** [qaprosoft/carina-demo#55]
Hi,

I was trying to launch test cases method by loading method class and then invoking method using method.invoke.
Below is the Test class 
```
public class MobileSampleTest extends AbstractTest {

	@Test(description = "JIRA#DEMO-0011")
	@MethodOwner(owner = "qpsdemo")
	public void testLoginUser(HashMap<String,Object> testDetail) throws Exception {
		setApplicationPath();
               AppiumDriver driver = (AppiumDriver) testDetail.get("appiumDriver");
		String username = "Test user";
		String password = RandomStringUtils.randomAlphabetic(10);
		WelcomePageBase welcomePage = initPage(driver, WelcomePageBase.class);
		Assert.assertTrue(welcomePage.isPageOpened(), "Welcome page isn't opened");
		LoginPageBase loginPage = welcomePage.clickNextBtn();
		Assert.assertFalse(loginPage.isLoginBtnActive(), "Login button is active");
//		loginPage.typeName(username);
//		loginPage.typePassword(password);
		loginPage.selectMaleSex();
		loginPage.checkPrivacyPolicyCheckbox();
		CarinaDescriptionPageBase carinaDescriptionPage = loginPage.clickLoginBtn();
		Assert.assertTrue(carinaDescriptionPage.isPageOpened(), "Carina description page isn't opened");
	}

	private void setApplicationPath() {
		String pathToApp;
		String iosPath = "src/main/resources/carinademoexample.zip";
		String androidPath = "src/main/resources/carinademoexample.apk";
		if (Type.ANDROID_PHONE.getFamily().equalsIgnoreCase(R.CONFIG.get("capabilities.platformName")))
			pathToApp = androidPath;
		else 
			pathToApp = iosPath;
		File file = new File(pathToApp);
		Configuration.setMobileApp(file.getAbsolutePath());
	}
}
```

I want to pass hashmap with custom driver to method when invoking. I am using below code for launching test cases. 

```
public class CarinaTest {
	
	public static void main(String[] args) {
		try {	
			String classToLoad = "com.qaprosoft.carina.demo.MobileSampleTest";
			String methodToLoad = "testLoginUser";
			
			 AppiumDriver appiumDriver = appiumManager.getDriver();
	
		     HashMap<String, Object> methodPayload = new HashMap<String, Object>();
		     methodPayload.put("appiumDriver", appiumDriver);
		     methodPayload.put("testJobId", 1);
		     
				
			Class cls = Class.forName(classToLoad);
			Method[] methods = cls.getMethods();
			Object obj = cls.newInstance();
			for (Method method2 : methods) {					
				if(method2.getName().contains(methodToLoad.trim())) {
					method2.invoke(obj, methodPayload);
				}
			}			
		} catch (Exception e) {
			e.printStackTrace();
		}	
	}
	
}
```
I am getting below error while invoking method:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.RuntimeException: There is no any class that satisfy to required conditions: [parent class - com.qaprosoft.carina.demo.mobile.gui.pages.common.WelcomePageBase], [device type - DESKTOP]
	at com.qaprosoft.carina.core.foundation.utils.factory.ICustomTypePageFactory.initPage(ICustomTypePageFactory.java:111)
	at com.qaprosoft.carina.demo.MobileSampleTest.testLoginUser(MobileSampleTest.java:31)
	... 5 more
```

When I run test as testng suite it works fine. But I am not able to launch as mentioned above.
Any help would be appreciated.

Thanks

**Comment by vdelendik** [comment]
from quick overview test continue to use CustomTypePageFactory:
WelcomePageBase welcomePage = initPage(driver, WelcomePageBase.class);
http://qaprosoft.github.io/carina/automation/mobile/#how-to-use-customtypepagefactory

and according to the _config.properties param you are trying to launch again regular desktop browser, not a mobile app.
That's why ICustomTypepageFactory expects to see DESKTOP implementation of the page object.
The similar like this one but with parent DESKTOP: 
@DeviceType(pageType = Type.ANDROID_PHONE, parentClass = WelcomePageBase.class)

https://github.com/qaprosoft/carina-demo/blob/9f4803fc9736eb83a31bc3cc0c567d757ab3e2db/src/main/java/com/qaprosoft/carina/demo/mobile/gui/pages/android/WelcomePage.java#L11

so I recommend to take a look into the _config.properties to make sure you provide mobile testing capabilities

**Comment by vdelendik** [comment]
closing so far as no feedback received. feel free to open new one if it is still an issue
