### ISSUE TITLE
Problem in running demo project

### ISSUE THREAD

**Issue by navneetgarggate6** [qaprosoft/carina-demo#62]
I am following http://qaprosoft.github.io/carina/execution/ steps

To run the test suite from Eclipse IDE, just select the required TestNG xml file: Right click > Run As > TestNG suite

An internal error occurred during: "Launching carina-demo_src.test.resources.testng_suites.web.xml".
org.testng.eclipse.maven.MavenTestNGLaunchConfigurationProvider.getClasspath(Lorg/eclipse/debug/core/ILaunchConfiguration;)Ljava/util/List;

I also get following error after change the version of eclipse

------------- Driver capabilities -----------
================================================

java.lang.NoSuchMethodError: org.testng.TestRunner.addListener(Ljava/lang/Object;)V
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:32)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

**Comment by vdelendik** [comment]
@navneetgarggate6, you are trying to run tests using 6.9.10 TestNG somehow.
We don't have explicit dependency in carina-demo but transitively it should use 6.14.3.
Please investigate why are you trying to launch using old TestNG version.
